In [1]:
%matplotlib inline
print("hi")
import numpy as np
import matplotlib.pyplot as plot
import warnings
plot.style.use("fivethirtyeight")
from datascience import *

hi


In [2]:
pets = make_array("cat",'cat','dog','cat','dog','rabbit')
pets


array(['cat', 'cat', 'dog', 'cat', 'dog', 'rabbit'],
      dtype='<U6')

In [3]:
pets=='cat'

array([ True,  True, False,  True, False, False], dtype=bool)

In [4]:
np.sum(pets=='dog')


2

In [5]:
np.count_nonzero(pets=='dog')

2

In [6]:
x = np.arange(20,31,2)
x

array([20, 22, 24, 26, 28, 30])

In [7]:
x>28



array([False, False, False, False, False,  True], dtype=bool)

In [8]:
np.sum(x>28)

1

In [9]:
survey = Table.read_table(".csv/welcome_survey_sp22.csv")

In [10]:
survey.show

<bound method Table.show of Year   | Extroversion | Number of textees | Hours of sleep | Handedness   | Pant leg           | Sleep position     | Pets                           | Piercings
Second | 5            | 5                 | 8              | Left-handed  | Left leg in first  | On your left side  | Ants                           | 0
Fourth | 2            | 3                 | 7              | Right-handed | Left leg in first  | On your left side  | Beetles, Centipedes, Scorpions | 0
First  | 3            | 4                 | 8              | Right-handed | Right leg in first | On your back       | Bird                           | 0
Second | 4            | 8                 | 8              | Right-handed | Right leg in first | On your back       | Bird                           | 0
Second | 4            | 2                 | 6              | Right-handed | Right leg in first | On your right side | Bird                           | 0
Second | 5            | 4                 | 7 

In [11]:
survey.take(0)

Year   | Extroversion | Number of textees | Hours of sleep | Handedness  | Pant leg          | Sleep position    | Pets | Piercings
Second | 5            | 5                 | 8              | Left-handed | Left leg in first | On your left side | Ants | 0

In [12]:
survey.row(0)

Row(Year='Second', Extroversion=5, Number of textees=5, Hours of sleep=8.0, Handedness='Left-handed', Pant leg='Left leg in first', Sleep position='On your left side', Pets='Ants', Piercings=0)

In [13]:
survey.select(1,2,3) 

Extroversion | Number of textees | Hours of sleep
5            | 5                 | 8
2            | 3                 | 7
3            | 4                 | 8
4            | 8                 | 8
4            | 2                 | 6
5            | 4                 | 7
4            | 2                 | 8
4            | 4                 | 4
3            | 3                 | 7
2            | 2                 | 7
... (1333 rows omitted)

In [14]:
np.sum(survey.select(1,2,3).row(2))

15.0

In [15]:
survey.labels

('Year',
 'Extroversion',
 'Number of textees',
 'Hours of sleep',
 'Handedness',
 'Pant leg',
 'Sleep position',
 'Pets',
 'Piercings')

In [16]:
survey.show()

In [17]:
np.unique(survey.column("Sleep position"))

array(['On your back', 'On your left side', 'On your right side',
       'On your stomach'],
      dtype='<U18')

In [18]:
survey.pivot(4,5)

Pant leg           | Both | Left-handed | Right-handed
I don't know       | 1    | 10          | 185
Left leg in first  | 7    | 42          | 414
Right leg in first | 1    | 41          | 642

In [19]:
p=survey.pivot(6,3)
p

Hours of sleep | On your back | On your left side | On your right side | On your stomach
3              | 0            | 1                 | 1                  | 0
4              | 8            | 2                 | 4                  | 3
5              | 15           | 13                | 23                 | 9
5.5            | 1            | 0                 | 2                  | 0
6              | 51           | 87                | 91                 | 33
6.5            | 5            | 1                 | 5                  | 1
7              | 123          | 119               | 183                | 58
7.5            | 11           | 9                 | 5                  | 6
8              | 77           | 83                | 136                | 62
8.5            | 5            | 3                 | 2                  | 3
... (6 rows omitted)

In [20]:
p=p.with_column('total',p.drop(0).apply(np.sum))

In [21]:
p.plot("Hours of sleep","total")

In [22]:
trip = Table.read_table(".csv/trip.csv")

In [23]:
trip

Trip ID | Duration | Start Date      | Start Station                                 | Start Terminal | End Date        | End Station                                   | End Terminal | Bike # | Subscriber Type | Zip Code
913460  | 765      | 8/31/2015 23:26 | Harry Bridges Plaza (Ferry Building)          | 50             | 8/31/2015 23:39 | San Francisco Caltrain (Townsend at 4th)      | 70           | 288    | Subscriber      | 2139
913459  | 1036     | 8/31/2015 23:11 | San Antonio Shopping Center                   | 31             | 8/31/2015 23:28 | Mountain View City Hall                       | 27           | 35     | Subscriber      | 95032
913455  | 307      | 8/31/2015 23:13 | Post at Kearny                                | 47             | 8/31/2015 23:18 | 2nd at South Park                             | 64           | 468    | Subscriber      | 94107
913454  | 409      | 8/31/2015 23:10 | San Jose City Hall                            | 10             | 8/31/2015 23:17 | San Salvador at 1st                           | 8            | 68     | Subscriber      | 95113
913453  | 789      | 8/31/2015 23:09 | Embarcadero at Folsom                         | 51             | 8/31/2015 23:22 | Embarcadero at Sansome                        | 60           | 487    | Customer        | 9069
913452  | 293      | 8/31/2015 23:07 | Yerba Buena Center of the Arts (3rd @ Howard) | 68             | 8/31/2015 23:12 | San Francisco Caltrain (Townsend at 4th)      | 70           | 538    | Subscriber      | 94118
913451  | 896      | 8/31/2015 23:07 | Embarcadero at Folsom                         | 51             | 8/31/2015 23:22 | Embarcadero at Sansome                        | 60           | 363    | Customer        | 92562
913450  | 255      | 8/31/2015 22:16 | Embarcadero at Sansome                        | 60             | 8/31/2015 22:20 | Steuart at Market                             | 74           | 470    | Subscriber      | 94111
913449  | 126      | 8/31/2015 22:12 | Beale at Market                               | 56             | 8/31/2015 22:15 | Temporary Transbay Terminal (Howard at Beale) | 55           | 439    | Subscriber      | 94130
913448  | 932      | 8/31/2015 21:57 | Post at Kearny                                | 47             | 8/31/2015 22:12 | South Van Ness at Market                      | 66           | 472    | Subscriber      | 94702
... (243047 rows omitted)

In [24]:
trip.where("Start Station",are.equal_to,(trip.column("End Station")))
trip

Trip ID | Duration | Start Date      | Start Station                                 | Start Terminal | End Date        | End Station                                   | End Terminal | Bike # | Subscriber Type | Zip Code
913460  | 765      | 8/31/2015 23:26 | Harry Bridges Plaza (Ferry Building)          | 50             | 8/31/2015 23:39 | San Francisco Caltrain (Townsend at 4th)      | 70           | 288    | Subscriber      | 2139
913459  | 1036     | 8/31/2015 23:11 | San Antonio Shopping Center                   | 31             | 8/31/2015 23:28 | Mountain View City Hall                       | 27           | 35     | Subscriber      | 95032
913455  | 307      | 8/31/2015 23:13 | Post at Kearny                                | 47             | 8/31/2015 23:18 | 2nd at South Park                             | 64           | 468    | Subscriber      | 94107
913454  | 409      | 8/31/2015 23:10 | San Jose City Hall                            | 10             | 8/31/2015 23:17 | San Salvador at 1st                           | 8            | 68     | Subscriber      | 95113
913453  | 789      | 8/31/2015 23:09 | Embarcadero at Folsom                         | 51             | 8/31/2015 23:22 | Embarcadero at Sansome                        | 60           | 487    | Customer        | 9069
913452  | 293      | 8/31/2015 23:07 | Yerba Buena Center of the Arts (3rd @ Howard) | 68             | 8/31/2015 23:12 | San Francisco Caltrain (Townsend at 4th)      | 70           | 538    | Subscriber      | 94118
913451  | 896      | 8/31/2015 23:07 | Embarcadero at Folsom                         | 51             | 8/31/2015 23:22 | Embarcadero at Sansome                        | 60           | 363    | Customer        | 92562
913450  | 255      | 8/31/2015 22:16 | Embarcadero at Sansome                        | 60             | 8/31/2015 22:20 | Steuart at Market                             | 74           | 470    | Subscriber      | 94111
913449  | 126      | 8/31/2015 22:12 | Beale at Market                               | 56             | 8/31/2015 22:15 | Temporary Transbay Terminal (Howard at Beale) | 55           | 439    | Subscriber      | 94130
913448  | 932      | 8/31/2015 21:57 | Post at Kearny                                | 47             | 8/31/2015 22:12 | South Van Ness at Market                      | 66           | 472    | Subscriber      | 94702
... (243047 rows omitted)

In [28]:
def trip_wind(start,end):
    if (start==end):
        return "round print"
    else:
        return "one way"
kins = trip.with_column("Trip Kind", trip.apply(trip_wind, "Start Station", "End Station"))

In [29]:
kins.show(5)

In [36]:
kins.where("Duration", are.below(600)).pivot("Trip Kind", "Start Station")

Start Station                    | one way | round print
2nd at Folsom                    | 4583    | 18
2nd at South Park                | 3845    | 57
2nd at Townsend                  | 6385    | 50
5th at Howard                    | 3935    | 23
Adobe on Almaden                 | 300     | 6
Arena Green / SAP Center         | 238     | 13
Beale at Market                  | 3886    | 21
Broadway St at Battery St        | 3176    | 42
California Ave Caltrain Station  | 28      | 8
Castro Street and El Camino Real | 652     | 8
... (60 rows omitted)

In [72]:
def one_round(my,your):
    if(my>your):
        return 1
    elif(my < your):
        return -1
    else:
        return 0
    

In [73]:
one_round(4,3)

1

In [41]:
morning = make_array("wake up", "sleep in")

In [45]:
np.random.choice(morning)
np.random.choice(morning)


'wake up'

In [46]:
np.random.choice(morning, 7)

array(['sleep in', 'wake up', 'wake up', 'sleep in', 'sleep in', 'wake up',
       'wake up'],
      dtype='<U8')

In [64]:
np.sum((np.random.choice(morning,7) == 'wake up'))

5

In [65]:
a = np.random.choice(morning,7)

In [66]:
a


array(['sleep in', 'sleep in', 'sleep in', 'wake up', 'wake up', 'wake up',
       'wake up'],
      dtype='<U8')

In [67]:
np.sum(a=='wake up')

4

In [68]:
dice = np.arange(1,7)

In [69]:
dice


array([1, 2, 3, 4, 5, 6])

In [70]:
np.random.choice(dice)

2

In [ ]:
player1 